In [1]:
# Libraries 
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np
from auto_eda import AutoEDA

# Configuration
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_colwidth', None)
# pd.set_option('display.max_rows', None)

In [2]:
eda = AutoEDA()
df = eda.read_file('HR RAW DATA.csv')
eda.explo_df(df)

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
Index: 1614 entries, 0 to 1613
Data columns (total 41 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Age                       1614 non-null   object 
 1   Attrition                 1614 non-null   object 
 2   BusinessTravel            842 non-null    object 
 3   DailyRate                 1614 non-null   object 
 4   Department                302 non-null    object 
 5   DistanceFromHome          1614 non-null   int64  
 6   Education                 1614 non-null   int64  
 7   EducationField            869 non-null    object 
 8   employeecount             1614 non-null   int64  
 9   employeenumber            1183 non-null   object 
 10  EnvironmentSatisfaction   1614 non-null   int64  
 11  Gender                    1614 non-null   int64  
 12  HourlyRate                1614 non-null   object 
 13  JobInvolvement            1614 non-null   int

None


First 10 rows of the DataFrame:


Age Attrition     BusinessTravel DailyRate                Department  \
0  51        No                NaN    684,0$                       NaN   
1  52        No                NaN    699,0$                       NaN   
2  42        No      travel_rarely    532,0$   Research & Development    
3  47        No      travel_rarely    359,0$                       NaN   
4  46        No                NaN   1319,0$                       NaN   
5  48        No                NaN    117,0$   Research & Development    
6  59        No                NaN   1435,0$                       NaN   
7  42        No      travel_rarely    635,0$                       NaN   
8  41        No                NaN   1276,0$                       NaN   
9  41        No  travel_frequently    840,0$                       NaN   

   DistanceFromHome  Education    EducationField  employeecount  \
0                 6          3               NaN              1   
1                 1          4     Life Sciences              1   
2                 4          2  Technical Degree              1   
3                 2          4           Medical              1   
4                 3          3  Technical Degree              1   
5                22          3           Medical              1   
6                25          3     Life Sciences              1   
7                 1          1               NaN              1   
8                 2          5               NaN              1   
9                 9          3               NaN              1   

  employeenumber  EnvironmentSatisfaction  Gender HourlyRate  JobInvolvement  \
0          162,0                        1       0         51               3   
1          259,0                        3       0         65               2   
2          319,0                        3       0         58               3   
3            NaN                        1       1         82               3   
4            NaN                        1       1         45               4   
5         1900,0                        4       1         58               3   
6           81,0                        1       1         99               3   
7          387,0                        2       0         99               3   
8            NaN                        2       1         91               3   
9          999,0                        1       0         64               3   

   JobLevel              JobRole  JobSatisfaction MaritalStatus MonthlyIncome  \
0         5   resEArch DIREcToR                 3           NaN       19537,0   
1         5             ManAGeR                 3           NaN       19999,0   
2         5             ManaGER                 4       Married       19232,0   
3         4   ReseArCH DIrECtOr                 3       Married       17169,0   
4         4     sAleS EXECUtIve                 1      Divorced           NaN   
5         4             MANAger                 4           NaN       17174,0   
6         3     Sales ExeCutIVe                 1           NaN           NaN   
7         2     Sales eXEcUTiVe                 3       Married           NaN   
8         4             mANAGEr                 1       Married       16595,0   
9         5   reSEaRCH DIrectoR                 3           NaN           NaN   

   MonthlyRate  NUMCOMPANIESWORKED Over18 OverTime  PercentSalaryHike  \
0         6462                   7      Y       No                 13   
1         5678                   0    NaN      NaN                 14   
2         4933                   1    NaN       No                 11   
3        26703                   3      Y      NaN                 19   
4         7739                   2      Y       No                 12   
5         2437                   3    NaN       No                 11   
6         2354                   7      Y      NaN                 11   
7        24532                   1    NaN       No                 25   
8         5626     


Last 10 rows of the DataFrame:


Age Attrition     BusinessTravel DailyRate                Department  \
1604  41       Yes                NaN   1085,0$   Research & Development    
1605  31        No      travel_rarely    154,0$                       NaN   
1606  26        No  travel_frequently   1283,0$                    Sales    
1607  31        No                NaN    616,0$                       NaN   
1608  32        No                NaN    498,0$                       NaN   
1609  36       Yes      travel_rarely    530,0$                       NaN   
1610  45        No         non-travel    805,0$                       NaN   
1611  39        No      travel_rarely    903,0$                       NaN   
1612  36        No         non-travel   1229,0$                       NaN   
1613  46        No                NaN    566,0$                       NaN   

      DistanceFromHome  Education    EducationField  employeecount  \
1604                 2          4     Life Sciences              1   
1605                 7          4               NaN              1   
1606                 1          3           Medical              1   
1607                12          3           Medical              1   
1608                 3          4           Medical              1   
1609                 3          1     Life Sciences              1   
1610                 4          2               NaN              1   
1611               -13          5               NaN              1   
1612                 8          4  Technical Degree              1   
1613                 7          2           Medical              1   

     employeenumber  EnvironmentSatisfaction  Gender     HourlyRate  \
1604          927,0                        2       1  Not Available   
1605          941,0                        2       0  Not Available   
1606          956,0                        3       0             52   
1607            NaN                        4       1             41   
1608          966,0                        3       1             93   
1609          967,0                        3       0             51   
1610          972,0                        3       0             57   
1611            NaN                       13       0             41   
1612          990,0                        1       0             84   
1613            NaN                        4       0             75   

      JobInvolvement  JobLevel                      JobRole  JobSatisfaction  \
1604               1         1       LAbORAToRy tEcHNICian                 4   
1605               2         1        SAlES rEpreSENtaTiVe                 3   
1606               2         2             sAleS EXECUtIvE                 1   
1607               3         2   HEaltHCarE REPreSENtAtIve                 4   
1608               3         2      MANUfaCtuRiNG DiReCtor                 1   
1609               2         3             saLEs ExeCUTiVe                 4   
1610               3         2       LAboRaTOry tECHNiCIAn                 2   
1611               4         3             sAlES ExECUTivE                 3   
1612               3         2             SaLes ExecUtIVe                 4   
1613               3         3      mAnUfactURInG DiRECTOr                 3   

     MaritalStatus MonthlyIncome  MonthlyRate  NUMCOMPANIESWORKED Over18  \
1604      divorced           NaN        17725                   4    NaN   
1605           NaN        2329,0        11737                   3    NaN   
1606           NaN        4294,0        11148                   1      Y   
1607           NaN           NaN        17369                   0    NaN   
1608       Married        6725,0        13554                   1    NaN   
1609       Married       10325,0         5518                   1      Y   
1610           NaN        4447,0        23163                   1    NaN   
1611        Single           NaN         2560                   0    NaN   
1612      Divorced           NaN       


Statistical description of the DataFrame (numeric):


count          mean          std     min     25%  \
DistanceFromHome          1614.0      4.527261    14.591913   -49.0     2.0   
Education                 1614.0      2.925031     1.022357     1.0     2.0   
employeecount             1614.0      1.000000     0.000000     1.0     1.0   
EnvironmentSatisfaction   1614.0      4.294919     6.993559     1.0     2.0   
Gender                    1614.0      0.398389     0.489718     0.0     0.0   
JobInvolvement            1614.0      2.739777     0.711567     1.0     2.0   
JobLevel                  1614.0      2.068154     1.101344     1.0     1.0   
JobSatisfaction           1614.0      2.738538     1.106163     1.0     2.0   
MonthlyRate               1614.0  14284.495663  7110.414585  2094.0  8001.0   
NUMCOMPANIESWORKED        1614.0      2.673482     2.506152     0.0     1.0   
PercentSalaryHike         1614.0     15.165428     3.648610    11.0    12.0   
RelationshipSatisfaction  1614.0      2.704461     1.079031     1.0     2.0   
StockOptionLevel          1614.0      0.791202     0.842396     0.0     0.0   
TrainingTimesLastYear     1614.0      2.809789     1.297765     0.0     2.0   
YearsAtCompany            1614.0      7.132590     6.124237     0.0     3.0   
YearsSinceLastPromotion   1614.0      2.245973     3.235665     0.0     0.0   
YEARSWITHCURRMANAGER      1614.0      4.220570     3.562695     0.0     2.0   
DateBirth                 1614.0   1986.076208     9.101332  1963.0  1980.0   
NUMBERCHILDREN               0.0           NaN          NaN     NaN     NaN   

                              50%      75%      max  
DistanceFromHome              5.0     11.0     29.0  
Education                     3.0      4.0      5.0  
employeecount                 1.0      1.0      1.0  
EnvironmentSatisfaction       3.0      4.0     49.0  
Gender                        0.0      1.0      1.0  
JobInvolvement                3.0      3.0      4.0  
JobLevel                      2.0      3.0      5.0  
JobSatisfaction               3.0      4.0      4.0  
MonthlyRate               14248.5  20364.0  26999.0  
NUMCOMPANIESWORKED            2.0      4.0      9.0  
PercentSalaryHike            14.0     18.0     25.0  
RelationshipSatisfaction      3.0      4.0      4.0  
StockOptionLevel              1.0      1.0      3.0  
TrainingTimesLastYear         3.0      3.0      6.0  
YearsAtCompany                5.0      9.0     40.0  
YearsSinceLastPromotion       1.0      3.0     15.0  
YEARSWITHCURRMANAGER          3.0      7.0     17.0  
DateBirth                  1987.0   1993.0   2005.0  
NUMBERCHILDREN                NaN      NaN      NaN


Statistical description of the DataFrame (categorical):


count unique                       top  freq
Age                  1614     54                        35    84
Attrition            1614      2                        No  1355
BusinessTravel        842      3             travel_rarely   586
DailyRate            1614    849                      nan$   124
Department            302      3   Research & Development    196
EducationField        869      6             Life Sciences   349
employeenumber       1183   1079                    1195,0     2
HourlyRate           1614     72             Not Available    84
JobRole              1614   1579                  mANager      4
MaritalStatus         963      5                   Married   404
MonthlyIncome         771    668                    5304,0     4
Over18                713      1                         Y   713
OverTime              938      2                        No   682
PerformanceRating    1419      2                       3,0  1205
StandardHours         419      1                      80,0   419
TOTALWORKINGYEARS    1088     40                      10,0   144
WORKLIFEBALANCE      1506      4                       3,0   913
YearsInCurrentRole     34     10                       2,0    11
SameAsMonthlyIncome   771    668                    5304,0     4
Salary               1614      1               1000000000$  1614
RoleDepartament       302    301        MaNAgeR  -  Sales      2
RemoteWork           1614      5                         1   360


Count of null values per column:


Age                            0
Attrition                      0
BusinessTravel               772
DailyRate                      0
Department                  1312
DistanceFromHome               0
Education                      0
EducationField               745
employeecount                  0
employeenumber               431
EnvironmentSatisfaction        0
Gender                         0
HourlyRate                     0
JobInvolvement                 0
JobLevel                       0
JobRole                        0
JobSatisfaction                0
MaritalStatus                651
MonthlyIncome                843
MonthlyRate                    0
NUMCOMPANIESWORKED             0
Over18                       901
OverTime                     676
PercentSalaryHike              0
PerformanceRating            195
RelationshipSatisfaction       0
StandardHours               1195
StockOptionLevel               0
TOTALWORKINGYEARS            526
TrainingTimesLastYear          0
WORKLIFEBA


Percentage of null values per column (only columns with nulls):


BusinessTravel          47.83
Department              81.29
EducationField          46.16
employeenumber          26.70
MaritalStatus           40.33
MonthlyIncome           52.23
Over18                  55.82
OverTime                41.88
PerformanceRating       12.08
StandardHours           74.04
TOTALWORKINGYEARS       32.59
WORKLIFEBALANCE          6.69
YearsInCurrentRole      97.89
SameAsMonthlyIncome     52.23
RoleDepartament         81.29
NUMBERCHILDREN         100.00
dtype: float64


Rows with all values as null:
There is no rows with all values as null.

Count of duplicate rows:


np.int64(0)

In [21]:
eda.explo_df(df, column='SameAsMonthlyIncome')


Exploration of the column: SameAsMonthlyIncome

Statistical description (categorical):


count        771
unique       668
top       5304,0
freq           4
Name: SameAsMonthlyIncome, dtype: object


Count of null values:


np.int64(843)


Count of unique values:


668


Unique values:


array(['19537,0', '19999,0', '19232,0', '17169,0', nan, '17174,0',
       '16595,0', '19973,0', '13402,0', '13206,0', '19545,0', '18041,0',
       '19246,0', '10748,0', '16752,0', '6201,0', '19845,0', '4001,0',
       '10447,0', '16064,0', '3210,0', '10266,0', '10475,0', '6162,0',
       '4721,0', '4615,0', '16959,0', '10306,0', '5406,0', '5902,0',
       '10855,0', '5914,0', '6646,0', '13973,0', '13320,0', '6687,0',
       '4735,0', '13872,0', '19045,0', '16015,0', '9613,0', '11510,0',
       '4306,0', '17046,0', '5067,0', '3692,0', '19847,0', '2308,0',
       '5747,0', '10422,0', '6347,0', '2348,0', '3072,0', '12490,0',
       '8020,0', '17068,0', '8943,0', '19272,0', '5577,0', '2691,0',
       '7403,0', '8823,0', '3579,0', '17779,0', '18213,0', '13577,0',
       '19190,0', '17123,0', '19187,0', '10008,0', '7988,0', '7083,0',
       '4723,0', '3407,0', '2929,0', '12031,0', '15427,0', '5126,0',
       '9619,0', '5010,0', '19033,0', '10400,0', '2793,0', '5674,0',
       '19197,0', '841


Value Counts:


SameAsMonthlyIncome
5304,0     4
6347,0     4
2657,0     3
2258,0     3
2539,0     2
          ..
5151,0     1
2863,0     1
2858,0     1
1129,0     1
19845,0    1
Name: count, Length: 668, dtype: int64


Most frequent value (mode):


'5304,0'


Count of duplicates in the column:


np.int64(945)

In [4]:
for col in df.columns:
    eda.explo_df(df, column=col) 


Exploration of the column: Age

Statistical description (categorical):


count     1614
unique      54
top         35
freq        84
Name: Age, dtype: object


Count of null values:


np.int64(0)


Count of unique values:


54


Unique values:


array(['51', '52', '42', '47', '46', '48', '59', '41', '56', '38', '55',
       '40', '58', '35', '45', '33', '36', '34', 'forty-seven', '53',
       '43', '60', '32', '37', '49', '39', '50', '44', '30',
       'fifty-eight', '29', '31', '54', '57', '27', 'thirty-six', '28',
       '26', 'fifty-five', '25', 'fifty-two', 'thirty-one', '24',
       'thirty', '23', '22', '21', '20', 'twenty-six', '19',
       'thirty-seven', '18', 'thirty-two', 'twenty-four'], dtype=object)


Value Counts:


Age
35              84
34              83
31              82
29              78
36              74
38              64
32              64
30              63
33              61
40              60
27              54
28              53
37              53
42              50
45              48
41              46
39              45
26              45
43              40
46              38
44              34
50              31
25              27
24              26
47              26
49              25
55              24
51              20
48              20
53              20
54              20
52              18
56              17
22              16
21              16
23              15
58              14
20              11
59              10
19               9
18               8
60               5
57               5
thirty-two       2
forty-seven      1
fifty-eight      1
thirty-six       1
fifty-five       1
fifty-two        1
thirty-one       1
thirty           1
twenty-six       1
thirty-s


Most frequent value (mode):


'35'


Count of duplicates in the column:


np.int64(1560)


Exploration of the column: Attrition

Statistical description (categorical):


count     1614
unique       2
top         No
freq      1355
Name: Attrition, dtype: object


Count of null values:


np.int64(0)


Count of unique values:


2


Unique values:


array(['No', 'Yes'], dtype=object)


Value Counts:


Attrition
No     1355
Yes     259
Name: count, dtype: int64


Most frequent value (mode):


'No'


Count of duplicates in the column:


np.int64(1612)


Exploration of the column: BusinessTravel

Statistical description (categorical):


count               842
unique                3
top       travel_rarely
freq                586
Name: BusinessTravel, dtype: object


Count of null values:


np.int64(772)


Count of unique values:


3


Unique values:


array([nan, 'travel_rarely', 'travel_frequently', 'non-travel'],
      dtype=object)


Value Counts:


BusinessTravel
travel_rarely        586
travel_frequently    165
non-travel            91
Name: count, dtype: int64


Most frequent value (mode):


'travel_rarely'


Count of duplicates in the column:


np.int64(1610)


Exploration of the column: DailyRate

Statistical description (categorical):


count     1614
unique     849
top       nan$
freq       124
Name: DailyRate, dtype: object


Count of null values:


np.int64(0)


Count of unique values:


849


Unique values:


array(['684,0$', '699,0$', '532,0$', '359,0$', '1319,0$', '117,0$',
       '1435,0$', '635,0$', '1276,0$', '840,0$', '247,0$', '1369,0$',
       '201,0$', '1360,0$', '692,0$', '1398,0$', '286,0$', '1402,0$',
       '819,0$', '884,0$', '1238,0$', '515,0$', '1223,0$', '202,0$',
       '928,0$', '607,0$', '266,0$', '429,0$', '589,0$', 'nan$',
       '1180,0$', '1282,0$', '776,0$', '665,0$', '526,0$', '1034,0$',
       '1403,0$', '1499,0$', '580,0$', '859,0$', '263,0$', '1376,0$',
       '885,0$', '1003,0$', '1321,0$', '394,0$', '1372,0$', '1333,0$',
       '228,0$', '737,0$', '823,0$', '667,0$', '301,0$', '573,0$',
       '1329,0$', '630,0$', '1063,0$', '1017,0$', '1296,0$', '939,0$',
       '1355,0$', '1448,0$', '200,0$', '1202,0$', '404,0$', '208,0$',
       '813,0$', '465,0$', '1189,0$', '1001,0$', '1394,0$', '161,0$',
       '288,0$', '682,0$', '1354,0$', '147,0$', '119,0$', '1413,0$',
       '452,0$', '334,0$', '1132,0$', '982,0$', '480,0$', '1099,0$',
       '672,0$', '1379,0$', '58


Value Counts:


DailyRate
nan$       124
691,0$       7
329,0$       7
147,0$       6
530,0$       6
          ... 
1162,0$      1
845,0$       1
968,0$       1
830,0$       1
1423,0$      1
Name: count, Length: 849, dtype: int64


Most frequent value (mode):


'nan$'


Count of duplicates in the column:


np.int64(765)


Exploration of the column: Department

Statistical description (categorical):


count                          302
unique                           3
top        Research & Development 
freq                           196
Name: Department, dtype: object


Count of null values:


np.int64(1312)


Count of unique values:


3


Unique values:


array([nan, ' Research & Development ', ' Sales ', ' Human Resources '],
      dtype=object)


Value Counts:


Department
Research & Development     196
Sales                       91
Human Resources             15
Name: count, dtype: int64


Most frequent value (mode):


' Research & Development '


Count of duplicates in the column:


np.int64(1610)


Exploration of the column: DistanceFromHome

Statistical description (numeric):


count    1614.000000
mean        4.527261
std        14.591913
min       -49.000000
25%         2.000000
50%         5.000000
75%        11.000000
max        29.000000
Name: DistanceFromHome, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


69


Unique values:


array([  6,   1,   4,   2,   3,  22,  25,   9,   7,  23,  10,  12,  14,
       -13,  15,   8, -42,  28, -37,   5,  16, -35,  26, -26,  24,  29,
       -25,  17,  21, -18, -10, -30, -27,  20, -31, -29, -39,  18, -21,
       -15,  11,  13, -14,  19, -33, -34, -46, -36, -19,  27, -12, -23,
       -45, -28, -47, -32, -24, -16, -22, -41, -49, -11, -48, -38, -20,
       -17, -43, -40, -44])


Value Counts:


DistanceFromHome
 2     217
 1     203
 10     86
 9      85
 8      81
      ... 
-21      2
-43      2
-28      2
-39      1
-40      1
Name: count, Length: 69, dtype: int64


Most frequent value (mode):


np.int64(2)


Count of duplicates in the column:


np.int64(1545)


Exploration of the column: Education

Statistical description (numeric):


count    1614.000000
mean        2.925031
std         1.022357
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: Education, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


5


Unique values:


array([3, 4, 2, 1, 5])


Value Counts:


Education
3    621
4    445
2    314
1    180
5     54
Name: count, dtype: int64


Most frequent value (mode):


np.int64(3)


Count of duplicates in the column:


np.int64(1609)


Exploration of the column: EducationField

Statistical description (categorical):


count               869
unique                6
top       Life Sciences
freq                349
Name: EducationField, dtype: object


Count of null values:


np.int64(745)


Count of unique values:


6


Unique values:


array([nan, 'Life Sciences', 'Technical Degree', 'Medical', 'Other',
       'Marketing', 'Human Resources'], dtype=object)


Value Counts:


EducationField
Life Sciences       349
Medical             276
Marketing           104
Technical Degree     69
Other                59
Human Resources      12
Name: count, dtype: int64


Most frequent value (mode):


'Life Sciences'


Count of duplicates in the column:


np.int64(1607)


Exploration of the column: employeecount

Statistical description (numeric):


count    1614.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0
Name: employeecount, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


1


Unique values:


array([1])


Value Counts:


employeecount
1    1614
Name: count, dtype: int64


Most frequent value (mode):


np.int64(1)


Count of duplicates in the column:


np.int64(1613)


Exploration of the column: employeenumber

Statistical description (categorical):


count       1183
unique      1079
top       1195,0
freq           2
Name: employeenumber, dtype: object


Count of null values:


np.int64(431)


Count of unique values:


1079


Unique values:


array(['162,0', '259,0', '319,0', ..., '2012,0', '2023,0', '2040,0'],
      dtype=object)


Value Counts:


employeenumber
1195,0    2
1185,0    2
1162,0    2
1161,0    2
1160,0    2
         ..
1669,0    1
1673,0    1
1678,0    1
1697,0    1
58,0      1
Name: count, Length: 1079, dtype: int64


Most frequent value (mode):


'1044,0'


Count of duplicates in the column:


np.int64(534)


Exploration of the column: EnvironmentSatisfaction

Statistical description (numeric):


count    1614.000000
mean        4.294919
std         6.993559
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max        49.000000
Name: EnvironmentSatisfaction, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


38


Unique values:


array([ 1,  3,  4,  2, 42, 37, 35, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12,
       13, 28, 47, 36, 29, 24, 46, 16, 22, 41, 49, 11, 48, 18, 10, 45, 38,
       17, 20, 26, 43])


Value Counts:


EnvironmentSatisfaction
4     460
3     459
1     298
2     297
12      7
35      6
13      6
24      5
47      5
14      5
41      4
42      4
46      4
36      4
48      4
20      3
22      3
11      3
18      3
45      3
27      3
25      3
17      3
37      2
38      2
16      2
31      2
15      2
19      2
29      2
28      1
33      1
21      1
39      1
49      1
10      1
26      1
43      1
Name: count, dtype: int64


Most frequent value (mode):


np.int64(4)


Count of duplicates in the column:


np.int64(1576)


Exploration of the column: Gender

Statistical description (numeric):


count    1614.000000
mean        0.398389
std         0.489718
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000
Name: Gender, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


2


Unique values:


array([0, 1])


Value Counts:


Gender
0    971
1    643
Name: count, dtype: int64


Most frequent value (mode):


np.int64(0)


Count of duplicates in the column:


np.int64(1612)


Exploration of the column: HourlyRate

Statistical description (categorical):


count              1614
unique               72
top       Not Available
freq                 84
Name: HourlyRate, dtype: object


Count of null values:


np.int64(0)


Count of unique values:


72


Unique values:


array(['51', '65', '58', '82', '45', '99', '91', '64', '55', '68', '49',
       '61', '79', '31', '69', '48', '80', '74', '98', '59', '33', '56',
       '66', '57', '53', '87', '81', '84', '32', '41', '92', '47',
       'Not Available', '43', '86', '30', '42', '88', '96', '67', '62',
       '72', '78', '89', '52', '50', '90', '37', '94', '76', '60', '46',
       '83', '100', '40', '97', '54', '75', '39', '85', '63', '44', '93',
       '36', '35', '73', '71', '70', '38', '77', '95', '34'], dtype=object)


Value Counts:


HourlyRate
Not Available    84
42               33
66               32
48               30
84               29
                 ..
50               15
53               13
68               13
38               12
34               11
Name: count, Length: 72, dtype: int64


Most frequent value (mode):


'Not Available'


Count of duplicates in the column:


np.int64(1542)


Exploration of the column: JobInvolvement

Statistical description (numeric):


count    1614.000000
mean        2.739777
std         0.711567
min         1.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         4.000000
Name: JobInvolvement, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


4


Unique values:


array([3, 2, 4, 1])


Value Counts:


JobInvolvement
3    955
2    406
4    164
1     89
Name: count, dtype: int64


Most frequent value (mode):


np.int64(3)


Count of duplicates in the column:


np.int64(1610)


Exploration of the column: JobLevel

Statistical description (numeric):


count    1614.000000
mean        2.068154
std         1.101344
min         1.000000
25%         1.000000
50%         2.000000
75%         3.000000
max         5.000000
Name: JobLevel, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


5


Unique values:


array([5, 4, 3, 2, 1])


Value Counts:


JobLevel
2    597
1    586
3    242
4    113
5     76
Name: count, dtype: int64


Most frequent value (mode):


np.int64(2)


Count of duplicates in the column:


np.int64(1609)


Exploration of the column: JobRole

Statistical description (categorical):


count          1614
unique         1579
top        mANager 
freq              4
Name: JobRole, dtype: object


Count of null values:


np.int64(0)


Count of unique values:


1579


Unique values:


array([' resEArch DIREcToR ', ' ManAGeR ', ' ManaGER ', ...,
       ' sAlES ExECUTivE ', ' SaLes ExecUtIVe ',
       ' mAnUfactURInG DiRECTOr '], dtype=object)


Value Counts:


JobRole
mANager                       4
ManagEr                       3
mAnageR                       3
mAnaGeR                       3
MANAgER                       3
                             ..
human RESOurceS               1
SaLeS exEcUTiVE               1
ReSEArch scieNTiST            1
HEaLTHCArE rEpreSeNtatiVE     1
ReseaRCh dIRecTor             1
Name: count, Length: 1579, dtype: int64


Most frequent value (mode):


' mANager '


Count of duplicates in the column:


np.int64(35)


Exploration of the column: JobSatisfaction

Statistical description (numeric):


count    1614.000000
mean        2.738538
std         1.106163
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         4.000000
Name: JobSatisfaction, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


4


Unique values:


array([3, 4, 1, 2])


Value Counts:


JobSatisfaction
4    514
3    481
1    317
2    302
Name: count, dtype: int64


Most frequent value (mode):


np.int64(4)


Count of duplicates in the column:


np.int64(1610)


Exploration of the column: MaritalStatus

Statistical description (categorical):


count         963
unique          5
top       Married
freq          404
Name: MaritalStatus, dtype: object


Count of null values:


np.int64(651)


Count of unique values:


5


Unique values:


array([nan, 'Married', 'Divorced', 'Single', 'divorced', 'Marreid'],
      dtype=object)


Value Counts:


MaritalStatus
Married     404
Single      325
Divorced    188
Marreid      35
divorced     11
Name: count, dtype: int64


Most frequent value (mode):


'Married'


Count of duplicates in the column:


np.int64(1608)


Exploration of the column: MonthlyIncome

Statistical description (categorical):


count        771
unique       668
top       5304,0
freq           4
Name: MonthlyIncome, dtype: object


Count of null values:


np.int64(843)


Count of unique values:


668


Unique values:


array(['19537,0', '19999,0', '19232,0', '17169,0', nan, '17174,0',
       '16595,0', '19973,0', '13402,0', '13206,0', '19545,0', '18041,0',
       '19246,0', '10748,0', '16752,0', '6201,0', '19845,0', '4001,0',
       '10447,0', '16064,0', '3210,0', '10266,0', '10475,0', '6162,0',
       '4721,0', '4615,0', '16959,0', '10306,0', '5406,0', '5902,0',
       '10855,0', '5914,0', '6646,0', '13973,0', '13320,0', '6687,0',
       '4735,0', '13872,0', '19045,0', '16015,0', '9613,0', '11510,0',
       '4306,0', '17046,0', '5067,0', '3692,0', '19847,0', '2308,0',
       '5747,0', '10422,0', '6347,0', '2348,0', '3072,0', '12490,0',
       '8020,0', '17068,0', '8943,0', '19272,0', '5577,0', '2691,0',
       '7403,0', '8823,0', '3579,0', '17779,0', '18213,0', '13577,0',
       '19190,0', '17123,0', '19187,0', '10008,0', '7988,0', '7083,0',
       '4723,0', '3407,0', '2929,0', '12031,0', '15427,0', '5126,0',
       '9619,0', '5010,0', '19033,0', '10400,0', '2793,0', '5674,0',
       '19197,0', '841


Value Counts:


MonthlyIncome
5304,0     4
6347,0     4
2657,0     3
2258,0     3
2539,0     2
          ..
5151,0     1
2863,0     1
2858,0     1
1129,0     1
19845,0    1
Name: count, Length: 668, dtype: int64


Most frequent value (mode):


'5304,0'


Count of duplicates in the column:


np.int64(945)


Exploration of the column: MonthlyRate

Statistical description (numeric):


count     1614.000000
mean     14284.495663
std       7110.414585
min       2094.000000
25%       8001.000000
50%      14248.500000
75%      20364.000000
max      26999.000000
Name: MonthlyRate, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


1427


Unique values:


array([ 6462,  5678,  4933, ..., 15302, 26956, 16642])


Value Counts:


MonthlyRate
9150     4
6069     3
17001    3
9558     3
19373    3
        ..
10007    1
9128     1
24539    1
15587    1
7739     1
Name: count, Length: 1427, dtype: int64


Most frequent value (mode):


np.int64(9150)


Count of duplicates in the column:


np.int64(187)


Exploration of the column: NUMCOMPANIESWORKED

Statistical description (numeric):


count    1614.000000
mean        2.673482
std         2.506152
min         0.000000
25%         1.000000
50%         2.000000
75%         4.000000
max         9.000000
Name: NUMCOMPANIESWORKED, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


10


Unique values:


array([7, 0, 1, 3, 2, 4, 8, 9, 5, 6])


Value Counts:


NUMCOMPANIESWORKED
1    573
0    226
3    169
4    157
2    156
7     84
6     73
5     66
9     59
8     51
Name: count, dtype: int64


Most frequent value (mode):


np.int64(1)


Count of duplicates in the column:


np.int64(1604)


Exploration of the column: Over18

Statistical description (categorical):


count     713
unique      1
top         Y
freq      713
Name: Over18, dtype: object


Count of null values:


np.int64(901)


Count of unique values:


1


Unique values:


array(['Y', nan], dtype=object)


Value Counts:


Over18
Y    713
Name: count, dtype: int64


Most frequent value (mode):


'Y'


Count of duplicates in the column:


np.int64(1612)


Exploration of the column: OverTime

Statistical description (categorical):


count     938
unique      2
top        No
freq      682
Name: OverTime, dtype: object


Count of null values:


np.int64(676)


Count of unique values:


2


Unique values:


array(['No', nan, 'Yes'], dtype=object)


Value Counts:


OverTime
No     682
Yes    256
Name: count, dtype: int64


Most frequent value (mode):


'No'


Count of duplicates in the column:


np.int64(1611)


Exploration of the column: PercentSalaryHike

Statistical description (numeric):


count    1614.000000
mean       15.165428
std         3.648610
min        11.000000
25%        12.000000
50%        14.000000
75%        18.000000
max        25.000000
Name: PercentSalaryHike, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


15


Unique values:


array([13, 14, 11, 19, 12, 25, 16, 17, 22, 23, 20, 15, 21, 24, 18])


Value Counts:


PercentSalaryHike
11    232
13    230
12    225
14    220
15    110
18     98
17     88
16     86
19     82
20     60
22     59
21     51
23     29
24     25
25     19
Name: count, dtype: int64


Most frequent value (mode):


np.int64(11)


Count of duplicates in the column:


np.int64(1599)


Exploration of the column: PerformanceRating

Statistical description (categorical):


count     1419
unique       2
top        3,0
freq      1205
Name: PerformanceRating, dtype: object


Count of null values:


np.int64(195)


Count of unique values:


2


Unique values:


array(['3,0', '4,0', nan], dtype=object)


Value Counts:


PerformanceRating
3,0    1205
4,0     214
Name: count, dtype: int64


Most frequent value (mode):


'3,0'


Count of duplicates in the column:


np.int64(1611)


Exploration of the column: RelationshipSatisfaction

Statistical description (numeric):


count    1614.000000
mean        2.704461
std         1.079031
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         4.000000
Name: RelationshipSatisfaction, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


4


Unique values:


array([3, 1, 4, 2])


Value Counts:


RelationshipSatisfaction
3    504
4    468
2    339
1    303
Name: count, dtype: int64


Most frequent value (mode):


np.int64(3)


Count of duplicates in the column:


np.int64(1610)


Exploration of the column: StandardHours

Statistical description (categorical):


count      419
unique       1
top       80,0
freq       419
Name: StandardHours, dtype: object


Count of null values:


np.int64(1195)


Count of unique values:


1


Unique values:


array([nan, '80,0'], dtype=object)


Value Counts:


StandardHours
80,0    419
Name: count, dtype: int64


Most frequent value (mode):


'80,0'


Count of duplicates in the column:


np.int64(1612)


Exploration of the column: StockOptionLevel

Statistical description (numeric):


count    1614.000000
mean        0.791202
std         0.842396
min         0.000000
25%         0.000000
50%         1.000000
75%         1.000000
max         3.000000
Name: StockOptionLevel, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


4


Unique values:


array([0, 1, 2, 3])


Value Counts:


StockOptionLevel
0    687
1    666
2    172
3     89
Name: count, dtype: int64


Most frequent value (mode):


np.int64(0)


Count of duplicates in the column:


np.int64(1610)


Exploration of the column: TOTALWORKINGYEARS

Statistical description (categorical):


count     1088
unique      40
top       10,0
freq       144
Name: TOTALWORKINGYEARS, dtype: object


Count of null values:


np.int64(526)


Count of unique values:


40


Unique values:


array([nan, '34,0', '22,0', '28,0', '20,0', '21,0', '33,0', '40,0',
       '18,0', '25,0', '15,0', '17,0', '26,0', '16,0', '24,0', '14,0',
       '23,0', '27,0', '19,0', '11,0', '38,0', '37,0', '13,0', '12,0',
       '29,0', '10,0', '36,0', '35,0', '9,0', '31,0', '32,0', '8,0',
       '7,0', '30,0', '6,0', '5,0', '4,0', '3,0', '2,0', '1,0', '0,0'],
      dtype=object)


Value Counts:


TOTALWORKINGYEARS
10,0    144
8,0      86
6,0      84
9,0      69
5,0      66
7,0      56
4,0      54
1,0      53
12,0     34
3,0      32
13,0     30
14,0     30
11,0     29
16,0     28
15,0     28
20,0     28
18,0     27
21,0     23
17,0     22
2,0      21
22,0     18
19,0     17
24,0     14
28,0     13
23,0     13
0,0       8
26,0      8
33,0      6
36,0      6
29,0      6
25,0      6
27,0      5
37,0      5
31,0      4
32,0      3
40,0      3
30,0      3
35,0      3
34,0      2
38,0      1
Name: count, dtype: int64


Most frequent value (mode):


'10,0'


Count of duplicates in the column:


np.int64(1573)


Exploration of the column: TrainingTimesLastYear

Statistical description (numeric):


count    1614.000000
mean        2.809789
std         1.297765
min         0.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         6.000000
Name: TrainingTimesLastYear, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


7


Unique values:


array([5, 3, 2, 0, 1, 4, 6])


Value Counts:


TrainingTimesLastYear
2    598
3    534
4    137
5    136
1     77
6     72
0     60
Name: count, dtype: int64


Most frequent value (mode):


np.int64(2)


Count of duplicates in the column:


np.int64(1607)


Exploration of the column: WORKLIFEBALANCE

Statistical description (categorical):


count     1506
unique       4
top        3,0
freq       913
Name: WORKLIFEBALANCE, dtype: object


Count of null values:


np.int64(108)


Count of unique values:


4


Unique values:


array(['3,0', nan, '2,0', '4,0', '1,0'], dtype=object)


Value Counts:


WORKLIFEBALANCE
3,0    913
2,0    359
4,0    155
1,0     79
Name: count, dtype: int64


Most frequent value (mode):


'3,0'


Count of duplicates in the column:


np.int64(1609)


Exploration of the column: YearsAtCompany

Statistical description (numeric):


count    1614.000000
mean        7.132590
std         6.124237
min         0.000000
25%         3.000000
50%         5.000000
75%         9.000000
max        40.000000
Name: YearsAtCompany, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


37


Unique values:


array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0])


Value Counts:


YearsAtCompany
5     208
1     171
2     141
3     141
10    133
7     115
4     114
8     106
9      94
6      78
0      44
11     36
20     29
13     26
15     21
14     19
22     17
18     15
12     15
21     14
16     14
19     12
17      9
24      7
33      5
25      5
26      4
31      3
32      3
27      3
36      3
23      2
40      2
29      2
37      1
30      1
34      1
Name: count, dtype: int64


Most frequent value (mode):


np.int64(5)


Count of duplicates in the column:


np.int64(1577)


Exploration of the column: YearsInCurrentRole

Statistical description (categorical):


count      34
unique     10
top       2,0
freq       11
Name: YearsInCurrentRole, dtype: object


Count of null values:


np.int64(1580)


Count of unique values:


10


Unique values:


array([nan, '13,0', '12,0', '11,0', '7,0', '6,0', '4,0', '3,0', '2,0',
       '1,0', '0,0'], dtype=object)


Value Counts:


YearsInCurrentRole
2,0     11
7,0      5
0,0      4
4,0      3
1,0      3
11,0     2
6,0      2
3,0      2
12,0     1
13,0     1
Name: count, dtype: int64


Most frequent value (mode):


'2,0'


Count of duplicates in the column:


np.int64(1603)


Exploration of the column: YearsSinceLastPromotion

Statistical description (numeric):


count    1614.000000
mean        2.245973
std         3.235665
min         0.000000
25%         0.000000
50%         1.000000
75%         3.000000
max        15.000000
Name: YearsSinceLastPromotion, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


16


Unique values:


array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9])


Value Counts:


YearsSinceLastPromotion
0     625
1     384
2     177
7      93
4      67
3      62
5      53
6      37
11     26
8      20
9      18
15     15
12     11
14     10
13     10
10      6
Name: count, dtype: int64


Most frequent value (mode):


np.int64(0)


Count of duplicates in the column:


np.int64(1598)


Exploration of the column: YEARSWITHCURRMANAGER

Statistical description (numeric):


count    1614.000000
mean        4.220570
std         3.562695
min         0.000000
25%         2.000000
50%         3.000000
75%         7.000000
max        17.000000
Name: YEARSWITHCURRMANAGER, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


18


Unique values:


array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16])


Value Counts:


YEARSWITHCURRMANAGER
2     380
0     270
7     267
3     148
8     115
4     104
1      84
9      70
5      36
10     31
6      30
11     22
12     20
13     16
17      8
15      5
14      5
16      3
Name: count, dtype: int64


Most frequent value (mode):


np.int64(2)


Count of duplicates in the column:


np.int64(1596)


Exploration of the column: SameAsMonthlyIncome

Statistical description (categorical):


count        771
unique       668
top       5304,0
freq           4
Name: SameAsMonthlyIncome, dtype: object


Count of null values:


np.int64(843)


Count of unique values:


668


Unique values:


array(['19537,0', '19999,0', '19232,0', '17169,0', nan, '17174,0',
       '16595,0', '19973,0', '13402,0', '13206,0', '19545,0', '18041,0',
       '19246,0', '10748,0', '16752,0', '6201,0', '19845,0', '4001,0',
       '10447,0', '16064,0', '3210,0', '10266,0', '10475,0', '6162,0',
       '4721,0', '4615,0', '16959,0', '10306,0', '5406,0', '5902,0',
       '10855,0', '5914,0', '6646,0', '13973,0', '13320,0', '6687,0',
       '4735,0', '13872,0', '19045,0', '16015,0', '9613,0', '11510,0',
       '4306,0', '17046,0', '5067,0', '3692,0', '19847,0', '2308,0',
       '5747,0', '10422,0', '6347,0', '2348,0', '3072,0', '12490,0',
       '8020,0', '17068,0', '8943,0', '19272,0', '5577,0', '2691,0',
       '7403,0', '8823,0', '3579,0', '17779,0', '18213,0', '13577,0',
       '19190,0', '17123,0', '19187,0', '10008,0', '7988,0', '7083,0',
       '4723,0', '3407,0', '2929,0', '12031,0', '15427,0', '5126,0',
       '9619,0', '5010,0', '19033,0', '10400,0', '2793,0', '5674,0',
       '19197,0', '841


Value Counts:


SameAsMonthlyIncome
5304,0     4
6347,0     4
2657,0     3
2258,0     3
2539,0     2
          ..
5151,0     1
2863,0     1
2858,0     1
1129,0     1
19845,0    1
Name: count, Length: 668, dtype: int64


Most frequent value (mode):


'5304,0'


Count of duplicates in the column:


np.int64(945)


Exploration of the column: DateBirth

Statistical description (numeric):


count    1614.000000
mean     1986.076208
std         9.101332
min      1963.000000
25%      1980.000000
50%      1987.000000
75%      1993.000000
max      2005.000000
Name: DateBirth, dtype: float64


Count of null values:


np.int64(0)


Count of unique values:


43


Unique values:


array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005])


Value Counts:


DateBirth
1988    84
1989    83
1992    83
1994    78
1987    75
1991    65
1993    64
1985    64
1990    61
1983    60
1986    55
1996    54
1995    53
1981    50
1978    48
1982    46
1997    46
1984    45
1980    40
1977    38
1979    34
1973    31
1999    27
1976    27
1998    27
1974    25
1968    25
1972    20
1969    20
1970    20
1975    20
1971    19
1967    17
2002    16
2001    16
2000    15
1965    15
2003    11
1964    10
2004     9
2005     8
1963     5
1966     5
Name: count, dtype: int64


Most frequent value (mode):


np.int64(1988)


Count of duplicates in the column:


np.int64(1571)


Exploration of the column: Salary

Statistical description (categorical):


count            1614
unique              1
top       1000000000$
freq             1614
Name: Salary, dtype: object


Count of null values:


np.int64(0)


Count of unique values:


1


Unique values:


array(['1000000000$'], dtype=object)


Value Counts:


Salary
1000000000$    1614
Name: count, dtype: int64


Most frequent value (mode):


'1000000000$'


Count of duplicates in the column:


np.int64(1613)


Exploration of the column: RoleDepartament

Statistical description (categorical):


count                     302
unique                    301
top        MaNAgeR  -  Sales 
freq                        2
Name: RoleDepartament, dtype: object


Count of null values:


np.int64(1312)


Count of unique values:


301


Unique values:


array([nan, ' ManaGER  -  Research & Development ',
       ' MANAger  -  Research & Development ',
       ' heaLtHcArE repResENtATiVe  -  Research & Development ',
       ' saLEs exEcutIVe  -  Sales ', ' Sales ExECuTIVe  -  Sales ',
       ' heALthCArE RePResEntaTIVe  -  Research & Development ',
       ' lABORAtOry tECHnIcIan  -  Research & Development ',
       ' ManufactUrINg DiReCTOr  -  Research & Development ',
       ' SaleS eXEcUtIVE  -  Sales ',
       ' HEaLthcaRe rEprEsEnTAtiVe  -  Research & Development ',
       ' rESeArCH sCientIST  -  Research & Development ',
       ' healTHCAre rePREseNtATiVE  -  Research & Development ',
       ' mANaGer  -  Research & Development ',
       ' HEAltHCaRe REPreseNTatIve  -  Research & Development ',
       ' SaLeS eXECUTivE  -  Sales ',
       ' reSeARCH SCIEnTiST  -  Research & Development ',
       ' ReSearch DiRecTOR  -  Research & Development ',
       ' resEaRCh SciEnTist  -  Research & Development ',
       ' hUmaN REsoUrCes  -  H


Value Counts:


RoleDepartament
MaNAgeR  -  Sales                                        2
Sales ExECuTIVe  -  Sales                                1
heALthCArE RePResEntaTIVe  -  Research & Development     1
lABORAtOry tECHnIcIan  -  Research & Development         1
ManufactUrINg DiReCTOr  -  Research & Development        1
                                                        ..
ManUFACtURiNg DiRECTOr  -  Research & Development        1
ResEARcH DiReCToR  -  Research & Development             1
MANAgER  -  Research & Development                       1
labORATORY TechnIcIaN  -  Research & Development         1
heaLtHcArE repResENtATiVe  -  Research & Development     1
Name: count, Length: 301, dtype: int64


Most frequent value (mode):


' MaNAgeR  -  Sales '


Count of duplicates in the column:


np.int64(1312)


Exploration of the column: NUMBERCHILDREN

Statistical description (numeric):


count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: NUMBERCHILDREN, dtype: float64


Count of null values:


np.int64(1614)


Count of unique values:


0


Unique values:


array([nan])


Value Counts:


Series([], Name: count, dtype: int64)


Most frequent value (mode):


IndexError: single positional indexer is out-of-bounds

# NOTES / PREVIOUS CODES

In [8]:
def eda_summary(data):
    indexes = list(data.columns)
    cols = ['dtype', 'not_null_count', 'null_count', 'null_percent', 'duplicates', 'unique', 'top', 'freq', 'mean', 'std', 'min', 'max', '25%', '50%', '75%', 'description']

    data_eda = pd.DataFrame(index=indexes, columns=cols)

    descriptions = {
        'Age': 'La edad del empleado.',
        'Attrition': 'Indica si el empleado ha dejado la empresa ("No" significa que no ha dejado la empresa y "Yes" significa que ha dejado la empresa).',
        'BusinessTravel': 'Describe la frecuencia de los viajes relacionados con el trabajo del empleado (por ejemplo, "Travel_Rarely" para raramente).',
        'DailyRate': 'La tarifa diaria del empleado.',
        'Department': 'El departamento en el que trabaja el empleado (por ejemplo, "Research & Development", "Sales", etc.).',
        'DistanceFromHome': 'La distancia desde el hogar del empleado hasta su lugar de trabajo.',
        'Education': 'Nivel de educación del empleado (generalmente en una escala del 1 al 5).',
        'EducationField': 'El campo de educación del empleado.',
        'employeecount': 'Un contador que generalmente es 1 y se usa para contar empleados.',
        'employeenumber': 'Un número de identificación único para el empleado.',
        'EnvironmentSatisfaction': 'Nivel de satisfacción del empleado en relación con su entorno de trabajo. Con valores que estan comprendidos entre el 1 y el 4, siendo el 4 el nivel de máxima satisfacción.',
        'Gender': 'El género del empleado. Donde 0 corresponde con "hombre" y 1 con "mujer".',
        'HourlyRate': 'La tarifa por hora del empleado.',
        'JobInvolvement': 'Nivel de implicación del empleado en su trabajo.',
        'JobLevel': 'Nivel jerárquico del empleado en la empresa.',
        'JobRole': 'El rol o puesto de trabajo del empleado.',
        'JobSatisfaction': 'Nivel de satisfacción del empleado con su trabajo.',
        'MaritalStatus': 'El estado civil del empleado (por ejemplo, "Single", "Married", etc.).',
        'MonthlyIncome': 'Ingresos mensuales del empleado.',
        'MonthlyRate': 'Tasa mensual del empleado.',
        'NUMCOMPANIESWORKED': 'Número de compañías en las que el empleado ha trabajado.',
        'Over18': 'Indica si el empleado es mayor de 18 años.',
        'OverTime': 'Indica si el empleado trabaja horas extras ("Yes" para sí o "No" para no).',
        'PercentSalaryHike': 'El porcentaje de aumento salarial del empleado.',
        'PerformanceRating': 'Calificación de rendimiento del empleado.',
        'RelationshipSatisfaction': 'Nivel de satisfacción en las relaciones interpersonales del empleado.',
        'StandardHours': 'Las horas estándar de trabajo.',
        'StockOptionLevel': 'Nivel de opciones de compra de acciones del empleado.',
        'TOTALWORKINGYEARS': 'Total de años de experiencia laboral del empleado.',
        'TrainingTimesLastYear': 'Número de veces que el empleado recibió capacitación el año pasado.',
        'WORKLIFEBALANCE': 'Equilibrio entre trabajo y vida personal del empleado.',
        'YearsAtCompany': 'Años que el empleado ha trabajado en la empresa actual.',
        'YearsInCurrentRole': 'Años que el empleado ha estado en su puesto actual.',
        'YearsSinceLastPromotion': 'Años desde la última promoción del empleado.',
        'YEARSWITHCURRMANAGER': 'Años que el empleado ha estado bajo la supervisión del actual gerente.',
        'SameAsMonthlyIncome': 'Ingresos mensuales del empleado.',
        'DateBirth': 'Año de nacimiento del empleado (teniendo en cuenta que los datos fueron recogidos en el 2023).',
        'Salary': 'Salario de los empleados.',
        'RoleDepartament': 'El departamento y el rol del empleado.',
        'NUMBERCHILDREN': 'Número de hijos de los empleados.',
        'RemoteWork': 'Si el empleado puede teletrabajar o no.'
    }

    for var in indexes:
        data_eda.loc[var, 'dtype'] = data[var].dtype
        data_eda.loc[var, 'not_null_count'] = data[var].notnull().sum()
        data_eda.loc[var, 'null_count'] = data[var].isnull().sum()
        data_eda.loc[var, 'null_percent'] = str(round((data[var].isnull().sum() / len(data)) * 100, 2)) + '%'
        data_eda.loc[var, 'duplicates'] = data[var].duplicated().sum()
        data_eda.loc[var, 'unique'] = data[var].nunique() # if data[var].dtype == 'object' else None
        data_eda.loc[var, 'top'] = data[var].mode().iloc[0] if not data[var].mode().empty else None
        data_eda.loc[var, 'freq'] = data[var].value_counts().max() if not data[var].mode().empty else None
        data_eda.loc[var, 'mean'] = data[var].mean() if data[var].dtype in ['int64', 'float64'] else None
        data_eda.loc[var, 'std'] = data[var].std() if data[var].dtype in ['int64', 'float64'] else None
        data_eda.loc[var, 'min'] = data[var].min() if data[var].dtype in ['int64', 'float64'] else None
        data_eda.loc[var, 'max'] = data[var].max() if data[var].dtype in ['int64', 'float64'] else None
        data_eda.loc[var, '25%'] = data[var].quantile(0.25) if data[var].dtype in ['int64', 'float64'] else None
        data_eda.loc[var, '50%'] = data[var].median() if data[var].dtype in ['int64', 'float64'] else None
        data_eda.loc[var, '75%'] = data[var].quantile(0.75) if data[var].dtype in ['int64', 'float64'] else None
        data_eda.loc[var, 'description'] = descriptions.get(var, 'No description available')

    return data_eda

In [ ]:
df_initial_eda = eda_summary(df)

# Description column left alignment
df_initial_eda['description'] = df_initial_eda['description'].apply(lambda x: f'{x:<}')

df_initial_eda = df_initial_eda.style.set_table_styles({
    'description': [{'selector': '', 'props': [('text-align', 'left')]}]
})

df_initial_eda = df_initial_eda.set_table_styles({
    'description': [{'selector': 'th', 'props': [('text-align', 'left')]}]
}, overwrite=False)

df_initial_eda

In [12]:
df.loc[df['employeenumber'].duplicated(keep=False), :].sort_values(by='employeenumber')

In [13]:
null_columns = df.isnull().sum()[df.isnull().sum() > 0]
null_percent = pd.DataFrame(null_columns, columns=['null_total_qty'])
null_percent['null_percent'] = (round((null_percent['null_total_qty'] / 1614) * 100, 2)).apply(lambda x: f"{x}%")
null_percent

null_total_qty null_percent
BusinessTravel                  772       47.83%
Department                     1312       81.29%
EducationField                  745       46.16%
employeenumber                  431        26.7%
MaritalStatus                   651       40.33%
MonthlyIncome                   843       52.23%
Over18                          901       55.82%
OverTime                        676       41.88%
PerformanceRating               195       12.08%
StandardHours                  1195       74.04%
TOTALWORKINGYEARS               526       32.59%
WORKLIFEBALANCE                 108        6.69%
YearsInCurrentRole             1580       97.89%
SameAsMonthlyIncome             843       52.23%
RoleDepartament                1312       81.29%
NUMBERCHILDREN                 1614       100.0%